### ISSUE TITLE
error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'

### ISSUE THREAD

**Issue by insung3511** [insung3511/yolo-human#1]
error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'

**Comment by linghuchongDevil** [comment]
hi, have you solved this proplem? could you tell me how can I do?

**Comment by insung3511** [comment]
Sorry I think that problem is darknet model was not found. Thank you for interest in my project 😄
